#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getQueryAdvice
#define setDianruRequestLaseTimeWithUrl setPermitBroccoli
#define dianruViewload StartWithSnake
#define dianruStartEGOUpdate ServeButton
#define dianruSpendScoreResultCallback FallVoice
#define getDianruMainBounds getQueryCell
#define dianruObjectForKey CatchAchieve
#define dianruDidJumpedView LockPumpkin
#define YQL_V StartWithAchieve
#define getDianruAppId getMatchPlant
#define dianruFindview ReplaceBroccoli
#define YQLHttpActionExecer FowardBread
#define dianruWithMySelf CrashBelieve
#define YQLAlignCenter FowardCell
#define YQLANIMATION_TYPE QueryWhale
#define dianruQueryString IteratorPiano
#define dianruResizeToFit CompileView
#define dianruAddRefreshView HashTomato
#define YQLMacros CallProgress
#define dianruEnable ChangeSlider
#define dianruRequestBlock ParseSnake
#define dianruImageFor ProductPiano
#define dianruTimeout CloneAchieve
#define YQLTextureInfo WaitView
#define dianruExpire DeleteLaugh
#define YQLViewUnknow GetBear
#define dianruParseEvent ShowPlant
#define dianruParseFloat HashRadish
#define dianruDidReportedView PrintPlant
#define YQLTextureVertical CollectSnake
#define YQLReqestResultType CoverOnion
#define YQLViewCell ApendSnake
#define getDianruSpendScore getCutImage
#define YQLTextureHorizontal RunPumpkin
#define dianruShareIstance CrashTree
#define dianruActions GeneralSegment
#define dianruBuildWithName EndWithPlant
#define setDianruNode setMatchKilometer
#define dianruDuration DoPotato
#define YQLNotificationAction IndexTable
#define dianruExec BrushOnion
#define dianruLoadView BuildCache
#define dianruApplicationKey CollectTrumpet
#define addDianruStyle WaitSnake
#define dianruRequestSpace HashTrumpet
#define dianruCreate DecorateRadish
#define dianruContext GetVoice
#define dianruCancel BrushNoodles
#define YQLAlignLeft HoldLiberty
#define YQLViewText ShowSnake
#define initWithDianruContext initNextTree
#define dianruName IteratorCake
#define dianruParseTextAttr WaitChicken
#define getDianruMacAddress getKillSlider
#define setDianruArrowData setSetPumpkin
#define YQLHttpRequest DevelopAchieve
#define dianruSubview BorrowBread
#define setDianruDelegateNull setAnswerDessert
#define dianruReadNetDataTaskFor NeedTree
#define dianruStopLoadAnimation ParseToolBar
#define dianruFsPath LoadSwitch
#define dianruEnableUseRadius AddButton
#define dianruDidDataReceivedView ServeEgg
#define YQLActionNode BeatImage
#define dianruWakeup CoverCache
#define YQLFontBold CrashImage
#define YQLViewSection InviteCell
#define YQLUrlCache WaitTableViewCell
#define dianruMovieFinishedCallback ParseSwitch
#define YQLViewSimple GetExperience
#define dianruLoadData AnswerView
#define dianruHide ReplaceAchieve
#define dianruResult matchAlertView
#define dianruRemove BeatVoice
#define YQLFontStyle_ALL ShowWhale
#define YQLViewDelegate BorrowEgg
#define refreshDianruTableHeaderDidTriggerRefresh KillTableCell
#define dianruRect CloneNavigationBar
#define dianruStartRotation DecorateAdvice
#define YQLViewTable PermitNoise
#define addDianruChild CompareInterest
#define dianruPurge HashCache
#define YQLHttpAction KillParrot
#define YQLOPullRefreshLoading CollectRadish
#define dianruText CoverSlider
#define dianruImage StartWithCake
#define _dianruBuild CatchPumpkin
#define setDianruImageWithContent setEndWithLaugh
#define dianruExecuteAnimation AddToolBar
#define getDianruLocation getReadWebView
#define YQLRefreshTableHeaderDelegate InviteTableViewCell
#define dianruInitialize CompileAchieve
#define setDianruResult setMatchAlertView
#define YQLSectionView ReadCake
#define dianruStopEGOUpdate LookLaugh
#define YQLFontDELETE LoadForest
#define refreshDianruScrollViewDidEndDragging FindLiberty
#define dianruTimes CollectSlider
#define dianruParent MatchPotato
#define dianruHandleSingleFingerEvent PermitNavigationBar
#define YQLNode CreateCache
#define YQLScriptRunner CompareView
#define YQLAnimationView BeatTabBar
#define YQLViewAnimation DecorateCake
#define dianruTarget LoadPotato
#define getDianruQueryString getParseBroccoli
#define getDianruReportUrl getStudySnake
#define dianruParseActionNode BorrowWebView
#define dianruUpdateContent CompilePicker
#define dianruCutStr IndexKilometer
#define setDianruRefreshArrowImage setParseSubject
#define getDianruScore getCompileRice
#define YQLMediaView HashPlant
#define refreshDianruTableHeaderDataSourceIsLoading ProductDolphin
#define YQLTexture IndexBread
#define YQLViewInterstitial HashNoise
#define dianruUrl CloneParrot
#define dianruLocalIPAddress SleepNoise
#define refreshDianruScrollViewDataSourceDidFinishedLoading DoLiberty
#define dianruWebViewCallBack PutTableCell
#define dianruDataFor ReadImage
#define YQLDelegate BorrowActivityView
#define dianruFsDirectory AddAlertView
#define dianruEncryptWithText BrushCake
#define YQLTableSectionView LockTree
#define setDianruState setBrushPicker
#define dianruDecodeToUrl DanceSpider
#define dianruLocation doRice
#define YQLTextureType NeedLabel
#define dianruDidMainCloseView ParseChicken
#define dianruEvent CoverTree
#define YQLViewHtml ChangeFlower
#define YQLOPullRefreshPulling ProductFlower
#define dianruExit DecorateDamage
#define dianruParseBackground DevelopPiano
#define YQLViewRoot PrintParrot
#define YQLAction BeatNavigationBar
#define YQLFactory ReadVoice
#define YQLOrientation FallButton
#define dianruDidViewCloseView ShowFlower
#define dianruDeviceOrientationDidChange LookPlant
#define YQLTextureSimple NextAlertView
#define getDianruImage getCreateSpider
#define dianruRun CrashSnake
#define dianruWrite BeatEgg
#define YQLInterstitialView RunTableViewCell
#define dianruURLEncodedString HashFlower
#define dianruAppuserid PrintPiano
#define dianruExecOne BeatCountry
#define YQLViewAction DanceLiberty
#define getDianruMachineName getNextActivityView
#define dianruKeyForString BlowLabel
#define dianruShowLoadAnimation NextProgress
#define dianruWithData ReplaceCarrot
#define dianruMoviePlayerLoadStateChanged CompareParrot
#define dianruFrame matchBread
#define YQLSimpleView ApendBear
#define YQLUIModel AddFlower
#define dianruDeviceString DevelopKilometer
#define dianruCreateWithView ShowCarrot
#define dianruShow GeneralPiano
#define dianruOn MakeView
#define dianruReportData ServeFeature
#define dianruParseHex FunctionRice
#define dianruCacheTimeList BuildPicker
#define YQLScript ChangeEgg
#define dianruHTTPResultCallback CutOnion
#define dianruScoreResultCallback CutBelieve
#define dianruSuspend FunctionBread
#define getDianruTimestamp getLoadTable
#define dianruDelegate ShowDamage
#define dianruWithUrl ProductWindow
#define dianruWithRequst SleepToolBar
#define getDianruOSVersion getNextTabBar
#define dianruStartAni BlowSlider
#define YQLView BiteTrumpet
#define YQLFontStyleNode PutAchieve
#define dianruStopRotation BeatSpider
#define dianruDisposeContent ChangeVoice
#define dianruFindView FallEgg
#define dianruWithCallback FallInterest
#define dianruURLDecodedString LookNoodles
#define getDianruUserId getFunctionVoice
#define YQLTextureLoop DecorateAchieve
#define YQLViewNode ServeExperience
#define dianruNode matchKilometer
#define dianruStopAnimation CutEgg
#define dianruUrlToDecode SetNavigationBar
#define dianruParseInsets CutButton
#define YQLAlign HoldFeature
#define dianruRegistClickEvent AnswerLabel
#define YQLViewLoader CutMemory
#define refreshDianruScrollViewDidScroll MaintainLabel
#define YQLTextView SleepBear
#define YQLEncryptUtil ParseButton
#define YQLViewUtil CoverSpider
#define YQLRefreshTableView_LastRefresh MaintainNoise
#define YQLLabelUpdate PrintPicker
#define dianruView CompileSwitch
#define YQLFontNormal PutFlower
#define dianruDecryptWithText CallPumpkin
#define dianruDidViewOpenView IndexSubject
#define YQLContext IndexPicker
#define YQLGTMBase64 QueryLiberty
#define dianruParseStyleAttr CoverAchieve
#define YQLOPullRefreshNormal MakeCake
#define YQLTALKINGTYPE SleepVoice
#define YQLFontUnderLine IteratorButton
#define YQLSdkInfo DanceTomato
#define dianruContent indexImage
#define setDianruContent setIndexImage
#define dianruData ServePotato
#define dianruForKey CostLabel
#define onDianruAdClickADID WaitTrumpet
#define getDianruScreenFrame getNextWebView
#define dianruDoneLoadingTableViewData FowardCache
#define dianruClose PrintRadish
#define YQLTalkingDataAction CloneLiberty
#define dianruCode CoverTomato
#define refreshDianruLastUpdatedDate FallNoodles
#define getDianruHttpFail getInviteLiberty
#define YQL_TK_CLICK MaintainEgg
#define dianruImageResultCallback SleepMemory
#define YQLViewType HashSlider
#define dianruDecode ReadSegment
#define YQLTableCell GetPiano
#define YQLCacheRequest CompileFlower
#define YQL_TK_DISPLAY CostSnake
#define YQLStyleNode BorrowToolBar
#define YQLEngine ReplaceActivityView
#define dianruReadLocationDataTaskFor PermitPlant
#define dianruScreenRotation AddFeature
#define dianruEnableRequestWithUrl CollectFeature
#define YQLTextureFull KillTomato
#define YQLOpenAction DanceButton
#define YQLViewFactory CloneDamage
#define YQLBorder CutTableViewCell
#define YQLFileSystem DecorateCache
#define dianruIsModify ReadProgress
#define dianruCenter DoAlertView
#define YQLViewImage HoldSnake
#define dianruReloadTableViewDataSource CrashPicker
#define YQLDeviceInfo DeleteDolphin
#define dianruParseStyle EndWithAlertView
#define YQLFontStyle KillWindow
#define setDianruLocation getDoRice
#define dianruParseBorder FindPlant
#define dianruParseView FowardTableCell
#define dianruFormat InviteCountry
#define dianruObject KillImage
#define dianruDidClickedView BeatWebView
#define YQLAlignRight CloneMemory
#define dianruKey DanceSegment
#define dianruMasks CrashAlertView
#define YQLRefreshTableHeaderView CollectNoodles
#define dianruPadding BeatLaugh
#define dianruMethod ReadSnake
#define refreshDianruTableHeaderDataSourceLastUpdated SetWhale
#define dianruSpaceUrl DoTabBar
#define dianruWith BeatProgress
#define dianruDrawType MaintainSnake
#define dianruLocalWiFiAvailable CatchChicken
#define dianruSubviews ReplaceVoice
#define YQLPullRefreshState BiteDolphin
#define dianruLoadani FallTableViewCell
#define getDianruWithIDFA getCreateBelieve
#define dianruParseRect CloneInterest
#define dianruParseColor FowardDessert
#define dianruTimerAction CoverDessert
#define onDianruAdDisplayADID RunSpider
#define dianruTo CallRadish
#define dianruLoad ServeTable
#define YQLTalkingData CompileAlertView
#define dianruParseAlign CompileOnion
#define YQLHtmlView CallNoise
#define dianruDecodeOne BuildWebView
#define dianruBuild ReplaceEgg
#define addDianruEvent DevelopBroccoli
#define dianruChecksum2 NeedKilometer
#define dianruAddCallback MaintainNavigationBar
#define dianruChecksum1 IndexLaugh
#define dianruBind CallNavigationBar
#define dianruDrawTexture ShowTomato
#define setDianruImageWithUrl setApendPiano
#define isDianruJailbroken WaitSlider
#define dianruValue BiteTree
#define getDianruBaseUrl getReplaceBelieve
#define dianruCarrierName CallBread
#define dianruSubType MatchLabel
#define YQLTableView RunRice
#define dianruParseFontStyle WaitMemory
#define YQLViewMedia ParseRadish
#define dianruClearup BuildTomato
#define dianruAddCell FowardTree
#define dianruState brushPicker
#define YQLAlertAction PermitCountry
#define dianruCloseMain WaitAdvice
#define dianruType BuildRice
#define YQLUtil IteratorTree
#define YQLEventManager ChangeTomato
#define setDianruViewNode setDoFeature
#define setDianruFrame setMatchBread
#define YQLAnimationAction RunAchieve
#define YQL_TK_UNKNOW CollectCarrot
#define dianruCallback WaitTomato
#define YQLDataCache HoldTree
#define YQLLoader ApendButton
#define dianruStartAniType StartWithSlider
#define YQLOpenUDID CollectTree
#define YQLLocation NeedNoodles
#define YQL_H LockNoise
#define dianruUpdate BrushSnake
#define dianruParseViewType CatchSnake
#define dianruStartAnimation ShowImage
#define YQLImageView StudySubject
#define YQLSDK IndexSpider
#define YQLWebView LockBread
#define dianruParseTextureType BiteKilometer
#define dianruRequest FindAlertView
#define dianruCheckIsNeedModify ProductTomato
#define dianruFileIsExists ReadDolphin
#endif /*__DIANRU_OBCODE_H__*/
